# Generated by Django 3.0.8 on 2021-01-16 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treearea', '0002_remove_treearea_tea'),
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teas',
            name='tree_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treearea.TreeArea'),
        ),
    ]
