# Generated by Django 3.0.8 on 2021-01-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teas',
            name='tree_area',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
