# Generated by Django 3.0.8 on 2020-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teas',
            old_name='user_profile',
            new_name='userprofile',
        ),
        migrations.AddField(
            model_name='teas',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='teas/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='teas',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='teas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='teas',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
