# Generated by Django 3.0.8 on 2021-01-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teas',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
