# Generated by Django 3.0.8 on 2020-12-17 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20201217_0720'),
        ('teas', '0002_auto_20201216_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teas',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='teas',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='teas',
            name='secondary_owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_owner', to='userprofile.UserProfile'),
        ),
    ]
