# Generated by Django 3.0.8 on 2020-12-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_remove_userprofile_user'),
        ('teas', '0003_auto_20201217_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teas',
            name='secondary_owner_id',
        ),
        migrations.AlterField(
            model_name='teas',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
    ]
