# Generated by Django 3.0.8 on 2020-12-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0005_remove_teas_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teas',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
