# Generated by Django 3.0.8 on 2021-01-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_contentxxxx',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
