# Generated by Django 3.0.8 on 2021-01-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('acreage', models.FloatField(blank=True, max_length=20, null=True)),
                ('number_tea', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tree_area/%Y/%m/%d')),
                ('lat1', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lon1', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lat2', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lon2', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lat3', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lon3', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lat4', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lon4', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lat5', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lon5', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lat6', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lon6', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lat7', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lon7', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lat8', models.DecimalField(decimal_places=9, max_digits=15)),
                ('lon8', models.DecimalField(decimal_places=9, max_digits=15)),
            ],
        ),
    ]
