# Generated by Django 3.0.8 on 2021-01-29 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treearea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lat1',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lat2',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lat3',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lat4',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lat5',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lat6',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lat7',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lat8',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lon1',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lon2',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lon3',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lon4',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lon5',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lon6',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lon7',
        ),
        migrations.RemoveField(
            model_name='treearea',
            name='lon8',
        ),
        migrations.AddField(
            model_name='treearea',
            name='coordinate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treearea.Coordinate'),
        ),
    ]
