# Generated by Django 3.0.8 on 2021-01-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treearea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treearea',
            name='tea',
        ),
    ]
