# Generated by Django 3.0.8 on 2021-02-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treearea', '0003_auto_20210129_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treearea',
            name='number_tea',
        ),
    ]
