# Generated by Django 3.0.8 on 2021-01-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
    ]
