# Generated by Django 3.0.8 on 2021-01-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government',
            name='is_enable',
            field=models.BooleanField(default=False),
        ),
    ]
