# Generated by Django 3.0.8 on 2021-01-18 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210115_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userprofile.UserProfile')),
                ('is_enable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('userprofile.userprofile',),
        ),
    ]
