# Generated by Django 3.0.8 on 2020-12-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201216_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_owner',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_secondary_owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('secondary_owner', 'SecondaryOwner')], default='secondary_owner', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
