# Generated by Django 3.0.8 on 2020-12-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_remove_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('approved', 'approved'), ('reject', 'reject')], default='processing', max_length=20),
        ),
    ]
