# Generated by Django 3.0.8 on 2020-12-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0006_userprofile_status'),
        ('teas', '0004_auto_20201217_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(choices=[('processing', 'Processing'), ('approved', 'Approved'), ('reject', 'Reject')], default='processing', max_length=20)),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='userprofile.UserProfile')),
                ('secondary_owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_owner', to='userprofile.UserProfile')),
                ('tea_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teas.Teas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
